### ISSUE TITLE
Utilizar método de GORM addTo

### ISSUE THREAD

**Issue by fniwes** [ballcue/cumpleCompany#1]
Haciendo una rápida revisión de código encontré la existencia del método Empleado::agregarRegalo que hace un regalos.add(r)

Aunque el código no es incorrecto, es innecesario. Cuando se agrega una relación oneToMany GORM crea los métodos addTo* y removeFrom* que cumplen la misma función pero además se toma cuidado de algunos detalles extras.

Más información sobre este tema: http://grails.github.io/grails-doc/2.4.x/ref/Domain%20Classes/addTo.html

Además, entre menos código escriba, menos lugares para equivocarme y debuggear hay :smile:

**Comment by guidoarnone** [comment]
Genial, no conocía los métodos. Mañana a primera hora los implemento.

**Comment by fniwes** [comment]
Otra página que encontré interesante sobre el tema recientemente es http://spring.io/blog/2010/07/02/gorm-gotchas-part-2/
