### ISSUE TITLE
Utilizar findAllBy* en lugar de list().find

### ISSUE THREAD

**Issue by fniwes** [ballcue/cumpleCompany#2]
Utilizar findAllBy utiliza una búsqueda en la base de datos, a diferencia de utilizar list() que retorna todos los elementos en la tabla. Por lo tanto es mejor utilizar el findAllBy para filtrar a nivel de base datos que utilizar list() para recuperar todos los elementos y luego filtrar en groovy la colección.

https://github.com/ballcue/cumpleCompany/blob/8a9f1dbf9aca607a832f914c4f52139f047babed/grails-app/controllers/cumplecompany/EmpleadosController.groovy#L11

**Comment by guidoarnone** [comment]
Mañana a primera hora te consulto y lo cambio, estoy reemplazando el código por `Empleado previo = Empleado.findByDni{params.dni}` y el resultado es `null` aún cuando hay un empleado existente con ese DNI.

**Comment by fniwes** [comment]
Te envio la documentación de findBy*
http://grails.github.io/grails-doc/2.4.4/ref/Domain%20Classes/findBy.html

Básicamente, se usa como Empleado.findByDni( params.dni ), o sea no es con
llaves como si fuera un closure, sino que es una llamada a una función, por
lo tanto se usan paréntesis

2015-03-09 18:02 GMT-03:00 Guido Arnone <notifications@github.com>:

**Comment by guidoarnone** [comment]
Tiene sentido, leí la misma página varias veces y estaba dando por supuesto que era una closure, no me detuve a ver los paréntesis. Mil gracias! Si puedo cambiarlo más tarde lo actualizo, si no mañana lo antes posible.
