### ISSUE TITLE
Regalar en el día

### ISSUE THREAD

**Issue by lucasr20** [ballcue/cumpleCompany#6]
Cuando se hace un regalo en el día del cumpleaños lo toma para el año siguiente

**Comment by ballcue** [comment]
Ese es el comportamiento deseado, como dictado por la comisión directiva de cumpleCompany. Está basado en la idea de que el mismo día del cumpleaños ya es una fecha tardía para registrar un regalo cuya compra, obtención y entrega al cumpleañero aún quedaría pendiente.
