### ISSUE TITLE
Volver al home (detalle)

### ISSUE THREAD

**Issue by fcurdi** [ballcue/cumpleCompany#8]
No hay boton o forma clara de volver al inicio (en cualquier parte, mas aun si me arrepiento de regalar algo) (Se puede volver clickeando el logo o volviendo atras en el browser).

**Comment by ballcue** [comment]
Pero volver al home clickeando el logo es convención (ejemplos: Google. Facebook, Youtube, GitHub). Es el comportamiento deseado, buscando seguir esta convención mundial y un estilo minimalista en la página.
